name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [java, javascript, python]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JS dependencies and run tests
        if: matrix.language == 'javascript'
        run: |
          npm install
          npm run lint
          npm test

      - name: Set up Java
        if: matrix.language == 'java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Java tests
        if: matrix.language == 'java'
        run: ./gradlew test

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps and run tests
        if: matrix.language == 'python'
        run: |
          pip install -r requirements.txt
          flake8 .
          pytest
